import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, Alert, ScrollView, Text, TouchableOpacity, View } from 'react-native'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { ArrowLeft, Building2, CalendarDays, FileText, MessageSquare, Package, Truck, UserRound } from 'lucide-react-native'
import { useTheme } from '@/contexts/ThemeContext'
import { EmptyState } from '@/components/DataTable'
import { fetchPurchaseOrdersForSupplier, type PurchaseOrder } from '@/services/supplierService/supplierService'
import { getLink, updateLink, type SupplierLink, type SupplierLinkStatus } from '@/services/supplierLinkService'

type Tab = 'Overview' | 'Conversation' | 'Purchase Orders' | 'Deliveries' | 'Receipts' | 'Analytics' | 'Settings' | 'Activity'
const TABS: Tab[] = ['Overview', 'Conversation', 'Purchase Orders', 'Deliveries', 'Receipts', 'Analytics', 'Settings', 'Activity']
const money = (value: number) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP', maximumFractionDigits: 0 }).format(value)
const displayDate = (value?: string | null) => value ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium' }).format(new Date(value)) : 'Not available'

/** Relationship-specific collaboration workspace shared by supplier and retailer portals. */
export default function RelationshipWorkspaceScreen() {
  const { id } = useLocalSearchParams<{ id: string }>()
  const router = useRouter(); const { colors } = useTheme()
  const [tab, setTab] = useState<Tab>('Overview'); const [link, setLink] = useState<SupplierLink | null>(null)
  const [orders, setOrders] = useState<PurchaseOrder[]>([]); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => {
    if (!id) return
    try { setLoading(true); const current = await getLink(id); setLink(current); if (current) setOrders((await fetchPurchaseOrdersForSupplier(current.supplierOrgId)).filter(order => order.outlet.id === current.outletId)) }
    catch (error: any) { Alert.alert('Unable to open workspace', error?.message ?? 'Please try again.') }
    finally { setLoading(false) }
  }, [id])
  useEffect(() => { load() }, [load])
  const deliveries = useMemo(() => orders.filter(order => order.delivery), [orders])
  const setStatus = async (status: SupplierLinkStatus) => { if (!link) return; try { setLink(await updateLink(link.id, status)) } catch (error: any) { Alert.alert('Unable to update relationship', error?.message ?? 'Please try again.') } }
  if (loading) return <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }}><ActivityIndicator color={colors.primary} /></View>
  if (!link) return <View style={{ flex: 1, padding: 20, backgroundColor: colors.background }}><EmptyState title="Relationship not found" message="It may have been archived or you no longer have access." /></View>
  return <ScrollView style={{ flex: 1, backgroundColor: colors.background }} contentContainerStyle={{ padding: 20, gap: 16, maxWidth: 1440, width: '100%', alignSelf: 'center' }}>
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}><TouchableOpacity onPress={() => router.back()} accessibilityLabel="Back to supplier links" style={{ padding: 9, borderRadius: 10, backgroundColor: colors.sidebarMuted }}><ArrowLeft size={18} color={colors.text} /></TouchableOpacity><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontSize: 24, fontWeight: '800' }}>{link.organizationName}</Text><Text style={{ color: colors.textSecondary, marginTop: 3 }}>Relationship workspace · {link.status}</Text></View><TouchableOpacity onPress={() => setStatus(link.status === 'PAUSED' ? 'ACTIVE' : 'PAUSED')} style={{ paddingHorizontal: 12, paddingVertical: 10, borderRadius: 9, backgroundColor: colors.sidebarMuted }}><Text style={{ color: colors.text, fontWeight: '700' }}>{link.status === 'PAUSED' ? 'Resume' : 'Pause'}</Text></TouchableOpacity></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{TABS.map(item => <TouchableOpacity key={item} onPress={() => setTab(item)} style={{ paddingHorizontal: 13, paddingVertical: 9, borderRadius: 99, backgroundColor: tab === item ? colors.primary : colors.sidebarMuted }}><Text style={{ color: tab === item ? '#fff' : colors.textSecondary, fontSize: 12, fontWeight: '800' }}>{item}</Text></TouchableOpacity>)}</ScrollView>
    {tab === 'Overview' && <Overview link={link} colors={colors} onMessage={() => setTab('Conversation')} />}
    {tab === 'Purchase Orders' && <Orders orders={orders} colors={colors} />}
    {tab === 'Deliveries' && <Deliveries orders={deliveries} colors={colors} />}
    {tab === 'Analytics' && <Analytics link={link} orders={orders} colors={colors} />}
    {tab === 'Settings' && <Settings link={link} colors={colors} onStatus={setStatus} />}
    {tab === 'Activity' && <ActivityTimeline link={link} orders={orders} colors={colors} />}
    {tab === 'Conversation' && <EmptyState title="No messages in this relationship" message="Conversation history will appear here when either organization sends a message." />}
    {tab === 'Receipts' && <EmptyState title="No receipts shared" message="Receipts and invoices linked to this relationship will appear here." />}
  </ScrollView>
}

function Overview({ link, colors, onMessage }: { link: SupplierLink; colors: any; onMessage: () => void }) { const details = [[UserRound, 'Assigned agent', link.assignedAgentName ?? 'Unassigned'], [Building2, 'Warehouse', link.preferredWarehouseId ?? 'Not selected'], [Truck, 'Delivery instructions', link.deliveryInstructions ?? 'Not provided'], [CalendarDays, 'Receiving schedule', link.receivingHours ?? 'Not provided'], [FileText, 'Credit terms', link.creditTerms ?? 'Not specified']]; return <><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 12 }}>{[[money(link.revenue), 'Revenue'], [money(link.outstanding), 'Outstanding balance'], [String(link.orders), 'Orders'], [String(link.openMandates), 'Active mandates']].map(([value, label]) => <Metric key={label} value={value} label={label} colors={colors} />)}</View><View style={{ padding: 16, backgroundColor: colors.card, borderRadius: 14, borderWidth: 1, borderColor: colors.border, gap: 14 }}>{details.map(([Icon, label, value]: any) => <View key={label} style={{ flexDirection: 'row', gap: 10, alignItems: 'center' }}><Icon size={17} color={colors.primary} /><View><Text style={{ color: colors.textSecondary, fontSize: 11 }}>{label}</Text><Text style={{ color: colors.text, fontWeight: '700', marginTop: 2 }}>{value}</Text></View></View>)}</View><TouchableOpacity onPress={onMessage} style={{ alignSelf: 'flex-start', flexDirection: 'row', gap: 8, alignItems: 'center', backgroundColor: colors.primary, paddingHorizontal: 14, paddingVertical: 11, borderRadius: 10 }}><MessageSquare size={17} color="#fff" /><Text style={{ color: '#fff', fontWeight: '800' }}>Message</Text></TouchableOpacity></> }
function Orders({ orders, colors }: { orders: PurchaseOrder[]; colors: any }) { if (!orders.length) return <EmptyState title="No purchase orders" message="Purchase orders for this relationship will appear here." />; return <View style={{ gap: 9 }}>{orders.map(order => <Record key={order.id} icon={Package} title={order.poNumber} subtitle={`${order.status} · ${displayDate(order.createdAt)}`} value={money(order.totalAmount)} colors={colors} />)}</View> }
function Deliveries({ orders, colors }: { orders: PurchaseOrder[]; colors: any }) { if (!orders.length) return <EmptyState title="No deliveries" message="Delivery tracking for this relationship will appear here." />; return <View style={{ gap: 9 }}>{orders.map(order => <Record key={order.id} icon={Truck} title={order.poNumber} subtitle={`${order.delivery?.status ?? ''} · ${displayDate(order.delivery?.scheduledDate)}`} value={order.delivery?.driverName ?? 'Driver pending'} colors={colors} />)}</View> }
function Analytics({ link, orders, colors }: { link: SupplierLink; orders: PurchaseOrder[]; colors: any }) { const delivered = orders.filter(order => order.status === 'DELIVERED').length; const average = orders.length ? link.revenue / orders.length : 0; return <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 12 }}><Metric value={money(average)} label="Average order value" colors={colors} /><Metric value={`${orders.length ? Math.round((delivered / orders.length) * 100) : 0}%`} label="Delivery completion" colors={colors} /><Metric value={displayDate(link.linkedAt)} label="Customer since" colors={colors} /><Metric value={link.rating ? `${link.rating.toFixed(1)} / 5` : 'No rating'} label="Relationship rating" colors={colors} /></View> }
function Settings({ link, colors, onStatus }: { link: SupplierLink; colors: any; onStatus: (status: SupplierLinkStatus) => void }) { return <View style={{ gap: 10, padding: 16, borderRadius: 14, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border }}><Text style={{ color: colors.text, fontWeight: '800', fontSize: 17 }}>Relationship controls</Text><Text style={{ color: colors.textSecondary }}>Lifecycle changes are recorded in the relationship audit trail.</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{(['ACTIVE', 'PAUSED', 'ARCHIVED', 'BLOCKED'] as SupplierLinkStatus[]).map(status => <TouchableOpacity key={status} onPress={() => onStatus(status)} style={{ padding: 10, borderRadius: 9, backgroundColor: link.status === status ? colors.primary : colors.sidebarMuted }}><Text style={{ color: link.status === status ? '#fff' : colors.text, fontWeight: '700' }}>{status}</Text></TouchableOpacity>)}</View></View> }
function ActivityTimeline({ link, orders, colors }: { link: SupplierLink; orders: PurchaseOrder[]; colors: any }) { const entries = [{ title: 'Relationship created', at: link.createdAt }, ...orders.map(order => ({ title: `Purchase order ${order.poNumber} created`, at: order.createdAt })), { title: `Relationship updated to ${link.status}`, at: link.updatedAt }].filter(item => item.at).sort((a, b) => new Date(b.at as string).getTime() - new Date(a.at as string).getTime()); return <View style={{ gap: 10 }}>{entries.map((entry, index) => <View key={`${entry.title}-${index}`} style={{ flexDirection: 'row', gap: 10 }}><View style={{ width: 9, height: 9, borderRadius: 9, backgroundColor: colors.primary, marginTop: 5 }} /><View><Text style={{ color: colors.text, fontWeight: '700' }}>{entry.title}</Text><Text style={{ color: colors.textSecondary, fontSize: 12, marginTop: 3 }}>{displayDate(entry.at as string)}</Text></View></View>)}</View> }
function Metric({ value, label, colors }: { value: string; label: string; colors: any }) { return <View style={{ minWidth: 150, flexGrow: 1, padding: 15, borderRadius: 14, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border }}><Text style={{ color: colors.text, fontWeight: '800', fontSize: 18 }}>{value}</Text><Text style={{ color: colors.textSecondary, fontSize: 12, marginTop: 4 }}>{label}</Text></View> }
function Record({ icon: Icon, title, subtitle, value, colors }: { icon: any; title: string; subtitle: string; value: string; colors: any }) { return <View style={{ flexDirection: 'row', alignItems: 'center', gap: 11, padding: 14, backgroundColor: colors.card, borderRadius: 12, borderWidth: 1, borderColor: colors.border }}><Icon size={18} color={colors.primary} /><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: '800' }}>{title}</Text><Text style={{ color: colors.textSecondary, marginTop: 3, fontSize: 12 }}>{subtitle}</Text></View><Text style={{ color: colors.text, fontWeight: '700' }}>{value}</Text></View> }
