import React from 'react'
import { Image, Modal, Pressable, ScrollView, Text, TouchableOpacity, useWindowDimensions, View } from 'react-native'
import { Building2, MapPin, Store, X } from 'lucide-react-native'

import { useTheme } from '@/contexts/ThemeContext'
import type { SupplierLink } from '@/services/supplierLinkService'

const displayDate = (value?: string | null) => value ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not available'

export function SupplierLinkDetailsModal({ visible, link, portal, canEdit, onClose, onOpenCatalog, onAction }: { visible: boolean; link: SupplierLink | null; portal: 'supplier' | 'retailer'; canEdit: boolean; onClose: () => void; onOpenCatalog?: (link: SupplierLink) => void; onAction: (link: SupplierLink, action: 'approve' | 'reject' | 'disable' | 'acceptInvitation' | 'rejectInvitation') => void }) {
  const { colors } = useTheme(); const { width } = useWindowDimensions()
  if (!link) return null
  const details = [
    ['Retailer organization', link.retailerOrganizationName], ['Outlet', link.outletName], ['Outlet address', link.outletAddress ?? 'Not provided'],
    ['Supplier', link.supplierName], ['Supplier location', link.supplierLocation ?? 'Not provided'], ['Status', link.status],
    ['Requested', displayDate(link.requestedAt)], ['Approved', displayDate(link.approvedAt)], ['Rejected', displayDate(link.rejectedAt)], ['Disabled', displayDate(link.disabledAt)],
    ['Safe contact', link.retailerContactNumber ?? 'Not provided'],
  ]
  return <Modal transparent visible={visible} animationType="fade" onRequestClose={onClose}><Pressable onPress={onClose} style={{ flex: 1, backgroundColor: 'rgba(0,0,0,.55)', justifyContent: width < 600 ? 'flex-end' : 'center', alignItems: 'center', padding: width < 600 ? 0 : 24 }}><Pressable onPress={() => {}} style={{ width: '100%', maxWidth: 620, maxHeight: width < 600 ? '92%' : '86%', backgroundColor: colors.surface, borderTopLeftRadius: 18, borderTopRightRadius: 18, borderBottomLeftRadius: width < 600 ? 0 : 18, borderBottomRightRadius: width < 600 ? 0 : 18, borderWidth: 1, borderColor: colors.border, overflow: 'hidden' }}>
    <View style={{ flexDirection: 'row', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border }}><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontSize: 19, fontWeight: '900' }}>{portal === 'supplier' ? 'Retailer request profile' : 'Relationship details'}</Text><Text style={{ color: colors.textSecondary, marginTop: 3 }}>{portal === 'supplier' ? 'Review the requesting business and outlet.' : link.supplierName}</Text></View><TouchableOpacity onPress={onClose} accessibilityLabel="Close relationship details" style={{ minHeight: 44, minWidth: 44, alignItems: 'center', justifyContent: 'center' }}><X size={20} color={colors.text} /></TouchableOpacity></View>
    <ScrollView contentContainerStyle={{ padding: 16, gap: 10 }}>{portal === 'supplier' ? <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 13, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border }}>{link.retailerProfileImage ? <Image source={{ uri: link.retailerProfileImage }} style={{ width: 62, height: 62, borderRadius: 16, backgroundColor: colors.sidebarMuted }} /> : <View style={{ width: 62, height: 62, borderRadius: 16, backgroundColor: colors.sidebarMuted, alignItems: 'center', justifyContent: 'center' }}><Building2 size={27} color={colors.primary} /></View>}<View style={{ flex: 1 }}><Text style={{ color: colors.text, fontSize: 18, fontWeight: '900' }}>{link.retailerOrganizationName}</Text><View style={{ flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 5 }}><Store size={13} color={colors.textSecondary} /><Text style={{ color: colors.textSecondary }}>{link.outletName}</Text></View><View style={{ flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 4 }}><MapPin size={13} color={colors.textSecondary} /><Text style={{ color: colors.textSecondary, flex: 1 }}>{link.retailerLocation ?? link.outletAddress ?? 'Location not provided'}</Text></View></View></View> : null}{details.map(([label, value]) => <View key={label} style={{ flexDirection: 'row', justifyContent: 'space-between', gap: 18, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: colors.border }}><Text style={{ color: colors.textSecondary, fontSize: 12, fontWeight: '800' }}>{label}</Text><Text style={{ flex: 1, color: colors.text, textAlign: 'right' }}>{value}</Text></View>)}
      {link.status === 'PENDING' && ((canEdit && link.requestDirection === 'RETAILER_TO_SUPPLIER') || (portal === 'retailer' && link.requestDirection === 'SUPPLIER_TO_RETAILER')) ? <View style={{ flexDirection: 'row', gap: 9, marginTop: 8 }}><TouchableOpacity onPress={() => onAction(link, portal === 'retailer' ? 'acceptInvitation' : 'approve')} style={{ minHeight: 44, flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#059669' }}><Text style={{ color: '#fff', fontWeight: '900' }}>Approve</Text></TouchableOpacity><TouchableOpacity onPress={() => onAction(link, portal === 'retailer' ? 'rejectInvitation' : 'reject')} style={{ minHeight: 44, flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#DC2626' }}><Text style={{ color: '#fff', fontWeight: '900' }}>Reject</Text></TouchableOpacity></View> : null}
      {canEdit && link.status === 'APPROVED' ? <TouchableOpacity onPress={() => onAction(link, 'disable')} style={{ minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#DC2626', marginTop: 8 }}><Text style={{ color: '#fff', fontWeight: '900' }}>Disable relationship</Text></TouchableOpacity> : null}
      {portal === 'retailer' && link.status === 'APPROVED' && onOpenCatalog ? <TouchableOpacity onPress={() => onOpenCatalog(link)} style={{ minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: colors.primary, marginTop: 8 }}><Text style={{ color: '#fff', fontWeight: '900' }}>View Products / Order</Text></TouchableOpacity> : null}
    </ScrollView>
  </Pressable></Pressable></Modal>
}
