import React, { useState } from 'react'
import { Pressable, ScrollView, Text, View } from 'react-native'
import { BadgePercent, Banknote, Calculator, Receipt, Scale, Wallet } from 'lucide-react-native'
import { InsightCard } from '@/components/Kpi'
import { SkeletonBox } from '@/components/LoadingSkeleton'
import { useTheme } from '@/contexts/ThemeContext'
import { comparisonLabel, type SupplierAnalyticsData } from '@/services/supplierService/supplierAnalyticsService'
import type { FeeOptions, FeeSort } from '@/services/supplierService/supplierFinanceAnalytics'
import { AnalyticsDonut, RevenueTrendChart } from './AnalyticsCharts'
import { normalizeFeeTrendValue } from './feeTrendLine'

const php = (value: number) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(value)
const rate = (value: number | null) => value === null ? '—' : value.toFixed(3) + '%'
const SORTS: { key: FeeSort; label: string }[] = [{ key: 'SETTLED', label: 'Settled' }, { key: 'GROSS', label: 'Gross' }, { key: 'FEE', label: 'Fee' }, { key: 'NET', label: 'Net' }, { key: 'RATE', label: 'Rate' }]

function Panel({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  const { colors } = useTheme()
  return <View style={{ minWidth: 0, flexGrow: 1, padding: 18, gap: 14, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }}><View style={{ gap: 4 }}><Text style={{ color: colors.text, fontWeight: '800', fontSize: 15 }}>{title}</Text>{subtitle && <Text style={{ color: colors.textSecondary, fontSize: 12 }}>{subtitle}</Text>}</View>{children}</View>
}
function Choice({ label, selected, disabled, onPress }: { label: string; selected?: boolean; disabled?: boolean; onPress: () => void }) {
  const { colors } = useTheme()
  return <Pressable accessibilityRole="button" accessibilityState={{ selected, disabled }} disabled={disabled} onPress={onPress} style={{ minHeight: 44, justifyContent: 'center', paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: selected ? colors.primaryLight : colors.surface, opacity: disabled ? 0.5 : 1 }}><Text style={{ color: colors.text, fontSize: 12 }}>{label}</Text></Pressable>
}

export default function FeesAnalytics({ data, loading, busy, width, options, onOptionsChange }: { data: SupplierAnalyticsData | null; loading: boolean; busy: boolean; width: number; options: FeeOptions; onOptionsChange: (next: Partial<FeeOptions>) => void }) {
  const { colors } = useTheme(); const [allMetrics, setAllMetrics] = useState(false)
  const mobile = width < 680; const wide = width >= 1050; const columns = width >= 1250 ? 6 : width >= 680 ? 3 : width >= 440 ? 2 : 1
  const body = { color: colors.textSecondary, fontSize: 12 } as const
  if (loading) return <><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 12 }}>{Array.from({ length: mobile ? 4 : 6 }, (_, i) => <SkeletonBox key={i} style={{ height: 150, flexBasis: 190, flexGrow: 1 }} />)}</View><SkeletonBox style={{ height: 300 }} /><SkeletonBox style={{ height: 360 }} /></>
  if (!data) return null
  const fees = data.feeAnalytics; const current = fees.metrics; const previous = fees.previousMetrics; const page = fees.history
  const metrics = [
    { key: 'platformFees', label: 'Platform Fees', value: php(current.platformFees), prior: comparisonLabel(current.platformFees, previous.platformFees), icon: Receipt },
    { key: 'grossSettled', label: 'Settled Gross', value: php(current.grossSettled), prior: comparisonLabel(current.grossSettled, previous.grossSettled), icon: Banknote },
    { key: 'netEarnings', label: 'Supplier Net', value: php(current.netEarnings), prior: comparisonLabel(current.netEarnings, previous.netEarnings), icon: Wallet },
    { key: 'effectiveFeeRate', label: 'Effective Fee Rate', value: rate(current.effectiveFeeRate), prior: current.effectiveFeeRate === null || previous.effectiveFeeRate === null ? 'Unavailable' : comparisonLabel(current.effectiveFeeRate, previous.effectiveFeeRate), icon: BadgePercent },
    { key: 'averageFee', label: 'Average Fee', value: current.averageFee === null ? '—' : php(current.averageFee), prior: current.averageFee === null || previous.averageFee === null ? 'Unavailable' : comparisonLabel(current.averageFee, previous.averageFee), icon: Calculator },
    { key: 'settlementsWithFees', label: 'Settlements with Fees', value: current.settlementsWithFees.toLocaleString('en-PH'), prior: comparisonLabel(current.settlementsWithFees, previous.settlementsWithFees), icon: Scale },
  ]
  return <>
    <Text style={{ color: colors.text, fontSize: 20, fontWeight: '800' }}>Fees Analytics</Text><Text style={body}>{data.environment} · Asia/Manila · {data.range.startDate} – {data.range.endDate}</Text>
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -6, rowGap: 12 }}>{metrics.slice(0, mobile && !allMetrics ? 4 : 6).map(metric => <View key={metric.key} style={{ width: `${100 / columns}%`, paddingHorizontal: 6 }}><InsightCard title={metric.label} icon={metric.icon} accent="#FB7185" value={metric.value} valueFontSize={columns === 6 ? 16 : 20} subtitle={metric.prior + ' · vs. previous period'} subtitleColor={colors.textSecondary} /></View>)}</View>
    {mobile && <Choice label={allMetrics ? 'Show primary metrics' : 'View all metrics'} onPress={() => setAllMetrics(!allMetrics)} />}
    <Text style={body}>Historical fees come from immutable settled amounts and saved fee snapshots. Current fee rules are never used to reconstruct past fees. Gross = platform fee + supplier net.</Text>
    <View style={{ flexDirection: wide ? 'row' : 'column', gap: 14 }}><View style={{ flex: 3 }}><Panel title="Fee Trend" subtitle="Zero-filled settlement timeline; edge buckets may be partial."><RevenueTrendChart points={fees.trend.map(row => ({ bucket: row.bucket, grossSales: row.grossSettled, netEarnings: row.netEarnings, platformFees: normalizeFeeTrendValue(row.platformFees), settledOrders: row.settlementCount }))} feesOnly /><Text style={body}>{current.settlementCount ? php(current.platformFees) + ' fees across ' + current.settlementCount + ' settlements.' : 'No settled fee activity in this period.'}</Text></Panel></View><View style={{ flex: 2 }}><Panel title="Historical Fee Composition" subtitle="Rule type from each immutable settlement snapshot.">{fees.composition.length ? <AnalyticsDonut rows={fees.composition.map(row => ({ label: row.label, value: row.platformFees, percentage: row.percentage }))} center={php(current.platformFees)} caption="Fees" money /> : <Text style={{ ...body, textAlign: 'center', paddingVertical: 30 }}>No settled fees in this period.</Text>}</Panel></View></View>
    <View style={{ flexDirection: wide ? 'row' : 'column', gap: 14 }}><View style={{ flex: 3 }}><Panel title="Effective Fee Rate Trend" subtitle="Each bucket uses total fee ÷ total gross; individual rates are not averaged."><ScrollView style={{ maxHeight: 230 }} contentContainerStyle={{ gap: 8 }}>{fees.trend.filter(row => row.settlementCount > 0).map(row => <View key={row.bucket} style={{ flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: colors.border, paddingBottom: 8 }}><Text style={body}>{row.bucket} · {row.settlementCount} settlements</Text><Text style={{ color: colors.text, fontSize: 12, fontWeight: '800' }}>{rate(row.effectiveFeeRate)}</Text></View>)}</ScrollView>{!fees.trend.some(row => row.settlementCount) && <Text style={{ ...body, textAlign: 'center', paddingVertical: 24 }}>No rate is available without settled gross.</Text>}</Panel></View><View style={{ flex: 2 }}><Panel title="Highest Fee Settlements" subtitle="Top five immutable settlement fees.">{fees.highestFeeSettlements.map(row => <View key={row.id} style={{ borderBottomWidth: 1, borderColor: colors.border, paddingBottom: 9, gap: 3 }}><Text style={{ color: colors.text, fontSize: 12, fontWeight: '700' }}>{row.poNumber} · {php(row.fee)}</Text><Text style={body}>{php(row.gross)} gross · {rate(row.effectiveRate)}</Text></View>)}{!fees.highestFeeSettlements.length && <Text style={{ ...body, textAlign: 'center', paddingVertical: 24 }}>No settled fees in this period.</Text>}</Panel></View></View>
    <Panel title="Fee History" subtitle="Settlements only. Export contains this loaded page."><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 6 }}>{SORTS.map(sort => <Choice key={sort.key} label={'Sort: ' + sort.label} selected={options.feeSort === sort.key} disabled={busy} onPress={() => onOptionsChange({ feeSort: sort.key })} />)}</ScrollView><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 6 }}><Choice label={options.feeDirection === 'DESC' ? 'Descending ↓' : 'Ascending ↑'} disabled={busy} onPress={() => onOptionsChange({ feeDirection: options.feeDirection === 'DESC' ? 'ASC' : 'DESC' })} />{[20, 50, 100].map(limit => <Choice key={limit} label={limit + ' per page'} selected={options.feeLimit === limit} disabled={busy} onPress={() => onOptionsChange({ feeLimit: limit })} />)}</View>
      <View style={{ gap: 10 }}>{page.items.map(row => <View key={row.id} style={{ borderTopWidth: 1, borderColor: colors.border, paddingTop: 11, flexDirection: width >= 1100 ? 'row' : 'column', gap: 8 }}><Text style={{ color: colors.text, fontWeight: '700', flex: 1.2 }}>{row.poNumber}</Text><Text style={{ ...body, flex: 1.4 }}>{new Date(row.settledAt).toLocaleString('en-PH')}</Text><Text style={{ color: colors.text, fontSize: 12, flex: 1 }}>Fee {php(row.fee)}</Text><Text style={{ ...body, flex: 1 }}>Gross {php(row.gross)}</Text><Text style={{ ...body, flex: 1 }}>Net {php(row.net)}</Text><Text style={{ ...body, flex: 1 }}>{row.snapshotRateType ?? 'Rule unavailable'} · {rate(row.effectiveRate)}</Text></View>)}</View>
      {!page.items.length && <Text style={{ ...body, textAlign: 'center', paddingVertical: 24 }}>No fee settlements match this period and search.</Text>}<Text style={body}>{page.total} settlements · Page {page.page} of {page.totalPages}</Text><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}><Choice label="Previous page" disabled={busy || page.page <= 1} onPress={() => onOptionsChange({ feePage: page.page - 1 })} /><Choice label="Next page" disabled={busy || page.page >= page.totalPages} onPress={() => onOptionsChange({ feePage: page.page + 1 })} /></View></Panel>
  </>
}
