import React, { useState } from 'react'
import { Pressable, ScrollView, Text, View } from 'react-native'
import { CheckCircle2, Clock3, ListChecks, PackageCheck, Timer, Truck } from 'lucide-react-native'
import { LineChart } from 'react-native-chart-kit'
import { InsightCard } from '@/components/Kpi'
import { SkeletonBox } from '@/components/LoadingSkeleton'
import { useTheme } from '@/contexts/ThemeContext'
import { comparisonLabel, type SupplierAnalyticsData } from '@/services/supplierService/supplierAnalyticsService'
import type { OrderOptions, OrderPerformance, OrderSort } from '@/services/supplierService/supplierOrderAnalytics'
import { AnalyticsDonut } from './AnalyticsCharts'

const number = (value: number) => value.toLocaleString('en-PH', { maximumFractionDigits: 1 })
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString('en-PH', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }) : '—'
const hours = (value: number | null) => value === null ? '—' : value >= 24 ? (value / 24).toFixed(1) + ' days' : value.toFixed(1) + ' hours'
const SORTS: { key: OrderSort; label: string }[] = [{ key: 'CREATED', label: 'Created date' }, { key: 'COMPLETED', label: 'Completed date' }, { key: 'FULFILLMENT', label: 'Fulfillment time' }, { key: 'STATUS', label: 'Status' }, { key: 'AMOUNT', label: 'Order amount' }]

function Panel({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  const { colors } = useTheme()
  return <View style={{ flexGrow: 1, minWidth: 0, backgroundColor: colors.surface, borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 18, gap: 16 }}><View style={{ gap: 5 }}><Text style={{ color: colors.text, fontSize: 15, fontWeight: '800' }}>{title}</Text>{subtitle && <Text style={{ color: colors.textSecondary, fontSize: 12 }}>{subtitle}</Text>}</View>{children}</View>
}
function Empty({ children }: { children: string }) { const { colors } = useTheme(); return <Text style={{ color: colors.textSecondary, textAlign: 'center', fontSize: 13, paddingVertical: 24 }}>{children}</Text> }
function Choice({ label, onPress, selected = false, disabled = false }: { label: string; onPress: () => void; selected?: boolean; disabled?: boolean }) {
  const { colors } = useTheme()
  return <Pressable accessibilityRole="button" accessibilityState={{ selected, disabled }} disabled={disabled} onPress={onPress} style={{ minHeight: 44, justifyContent: 'center', paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: selected ? colors.primaryLight : colors.surface, opacity: disabled ? 0.5 : 1 }}><Text style={{ color: colors.text, fontSize: 12 }}>{label}</Text></Pressable>
}

function VolumeTrend({ points }: { points: SupplierAnalyticsData['orderAnalytics']['volumeTrend'] }) {
  const { colors } = useTheme()
  const [width, setWidth] = useState(0)
  const [selected, setSelected] = useState<number | null>(null)
  const stride = Math.max(1, Math.ceil(points.length / (width < 400 ? 5 : 7)))
  const active = selected === null ? null : points[selected]
  const hasActivity = points.some(point => point.created || point.completed)
  return <View onLayout={event => setWidth(event.nativeEvent.layout.width)} style={{ minWidth: 0, gap: 12 }}>
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 14 }}><Text style={{ color: '#168CFF', fontSize: 12 }}>● Created</Text><Text style={{ color: '#00D8A4', fontSize: 12 }}>● Completed</Text></View>
    {width > 0 && points.length > 0 && <View style={{ overflow: 'hidden' }}><LineChart width={width} height={220} fromZero withOuterLines={false} withVerticalLines={false} withShadow={hasActivity} withDots={hasActivity} data={{ labels: points.map((point, index) => index % stride === 0 ? new Date(point.bucket + 'T12:00:00').toLocaleDateString('en-PH', { month: 'short', day: 'numeric' }) : ''), datasets: [{ data: points.map(point => point.created), color: () => '#168CFF' }, { data: points.map(point => point.completed), color: () => '#00D8A4' }] }} chartConfig={{ backgroundGradientFrom: colors.surface, backgroundGradientTo: colors.surface, color: () => '#168CFF', labelColor: () => colors.textSecondary, decimalPlaces: 0, propsForBackgroundLines: { stroke: colors.border }, propsForLabels: { fontSize: width < 400 ? 10 : 11 }, useShadowColorFromDataset: true, fillShadowGradientOpacity: 0.1 }} getDotProps={(_value, index) => ({ r: points[index] && (points[index].created || points[index].completed) ? 3 : 0 })} onDataPointClick={({ index }) => setSelected(index)} /></View>}
    <Text accessibilityLiveRegion="polite" style={{ minHeight: 20, color: colors.textSecondary, fontSize: 12 }}>{!hasActivity ? 'No orders were created in this period.' : active ? active.bucket + ' · ' + number(active.created) + ' created · ' + number(active.completed) + ' completed' : 'Created uses PO creation date; completed uses buyer confirmation date.'}</Text>
  </View>
}

function OrderRows({ rows, table, onView }: { rows: OrderPerformance[]; table: boolean; onView: (id: string) => void }) {
  const { colors } = useTheme()
  const labels = ['PO #', 'Created', 'Buyer', 'Status', 'Items', 'Confirmation', 'Payment', 'Delivery', 'Fulfillment', 'Action']
  const widths = [1.1, 1.15, 1.3, 1, 0.45, 1, 0.8, 0.85, 0.9, 0.5]
  return <View style={{ gap: table ? 0 : 12 }}>{table && <View style={{ flexDirection: 'row', gap: 8, paddingBottom: 12 }}>{labels.map((label, index) => <Text key={label} style={{ color: colors.textSecondary, fontWeight: '700', fontSize: 10, flex: widths[index] }}>{label}</Text>)}</View>}{rows.map(order => {
    const cells = [order.poNumber, dateTime(order.createdAt), order.buyerName, order.status.replace(/_/g, ' '), number(order.itemCount), order.supplierConfirmation.replace(/_/g, ' '), order.paymentStatus.replace(/_/g, ' '), order.deliveryStatus.replace(/_/g, ' '), hours(order.fulfillmentHours)]
    return table ? <View key={order.id} style={{ flexDirection: 'row', gap: 8, paddingVertical: 14, borderTopWidth: 1, borderColor: colors.border }}>{cells.map((value, index) => <Text key={index} style={{ color: colors.text, fontSize: 10, flex: widths[index] }}>{value}</Text>)}<Pressable accessibilityRole="button" accessibilityLabel={'View order ' + order.poNumber} onPress={() => onView(order.id)} style={{ flex: widths[9], minHeight: 30, justifyContent: 'center' }}><Text style={{ color: colors.primary, fontSize: 11 }}>View</Text></Pressable></View>
      : <View key={order.id} style={{ borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: 14, gap: 9 }}><Text style={{ color: colors.text, fontWeight: '800', fontSize: 14 }}>{order.poNumber}</Text><Text style={{ color: colors.textSecondary, fontSize: 12 }}>{order.buyerName}</Text>{cells.slice(1).map((value, index) => <View key={labels[index + 1]} style={{ flexDirection: 'row', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 }}><Text style={{ color: colors.textSecondary, fontSize: 12 }}>{labels[index + 1]}</Text><Text style={{ color: colors.text, fontSize: 12, fontWeight: '600' }}>{value}</Text></View>)}<Pressable accessibilityRole="button" onPress={() => onView(order.id)} style={{ minHeight: 36, justifyContent: 'center' }}><Text style={{ color: colors.primary, fontSize: 12, fontWeight: '700' }}>View Order</Text></Pressable></View>
  })}</View>
}

export default function OrdersAnalytics({ data, loading, busy, width, options, onOptionsChange, onView }: { data: SupplierAnalyticsData | null; loading: boolean; busy: boolean; width: number; options: OrderOptions; onOptionsChange: (next: Partial<OrderOptions>) => void; onView: (id: string) => void }) {
  const { colors } = useTheme()
  const [allMetrics, setAllMetrics] = useState(false)
  const mobile = width < 680
  const wide = width >= 1100
  const columns = width >= 1250 ? 6 : width >= 680 ? 3 : width >= 440 ? 2 : 1
  const body = { color: colors.textSecondary, fontSize: 12 } as const
  if (loading) return <><View style={{ flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -6, rowGap: 12 }}>{Array.from({ length: mobile ? 4 : 6 }, (_, index) => <View key={index} style={{ width: `${100 / columns}%`, paddingHorizontal: 6 }}><SkeletonBox style={{ height: 154 }} /></View>)}</View><SkeletonBox style={{ height: 360 }} /><SkeletonBox style={{ height: 280 }} /><SkeletonBox style={{ height: 400 }} /></>
  if (!data) return null
  const orders = data.orderAnalytics
  const current = orders.metrics
  const previous = orders.previousMetrics
  const durationChange = current.averageFulfillmentHours === null || previous.averageFulfillmentHours === null || previous.averageFulfillmentHours === 0 ? 'Unavailable in previous period' : (Math.abs((current.averageFulfillmentHours - previous.averageFulfillmentHours) / previous.averageFulfillmentHours * 100).toFixed(1) + '% ' + (current.averageFulfillmentHours < previous.averageFulfillmentHours ? 'faster' : 'slower'))
  const metrics = [
    { key: 'totalOrders', label: 'Total Orders', icon: ListChecks, value: number(current.totalOrders), prior: comparisonLabel(current.totalOrders, previous.totalOrders) },
    { key: 'completedOrders', label: 'Completed Orders', icon: CheckCircle2, value: number(current.completedOrders), prior: comparisonLabel(current.completedOrders, previous.completedOrders) },
    { key: 'inProgressOrders', label: 'In Progress', icon: PackageCheck, value: number(current.inProgressOrders), prior: comparisonLabel(current.inProgressOrders, previous.inProgressOrders) },
    { key: 'cancelledRejected', label: 'Cancelled / Rejected', icon: Clock3, value: number(current.cancelledRejected), prior: comparisonLabel(current.cancelledRejected, previous.cancelledRejected) },
    { key: 'completionRate', label: 'Completion Rate', icon: Truck, value: current.completionRate === null ? '—' : current.completionRate.toFixed(1) + '%', prior: current.completionRate === null || previous.completionRate === null ? 'Unavailable without orders' : comparisonLabel(current.completionRate, previous.completionRate) },
    { key: 'averageFulfillmentHours', label: 'Average Fulfillment', icon: Timer, value: hours(current.averageFulfillmentHours), prior: durationChange },
  ]
  const chartKey = data.range.startDate + data.range.endDate + data.search
  const page = orders.performance
  return <>
    <Text style={{ color: colors.text, fontSize: 20, fontWeight: '800' }}>Orders Analytics</Text><Text style={body}>{data.environment} · Asia/Manila · {data.range.startDate} – {data.range.endDate} · Compared with {data.comparisonRange.startDate} – {data.comparisonRange.endDate}</Text>
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -6, rowGap: 12 }}>{metrics.slice(0, mobile && !allMetrics ? 4 : 6).map(metric => <View key={metric.key} style={{ width: `${100 / columns}%`, paddingHorizontal: 6 }}><InsightCard title={metric.label} icon={metric.icon} accent={colors.primary} value={metric.value} valueFontSize={columns === 6 ? 17 : columns >= 2 ? 18 : 24} subtitleColor={colors.textSecondary} subtitle={metric.prior + ' · vs. previous period'} /></View>)}</View>
    {mobile && <Choice label={allMetrics ? 'Show primary metrics' : 'View all metrics'} onPress={() => setAllMetrics(!allMetrics)} />}
    <Text style={body}>Order metrics are based on orders created in the selected period unless otherwise labelled. Completion Rate = completed orders ÷ total orders. Fulfillment time uses supplier confirmation through buyer confirmation only when both persisted timestamps are valid.</Text>
    {current.invalidDurationCount > 0 && <Text style={body}>{number(current.invalidDurationCount)} completed orders with impossible fulfillment timestamps were excluded.</Text>}
    <View style={{ flexDirection: wide ? 'row' : 'column', gap: 14 }}><View style={{ flex: wide ? 3 : undefined, minWidth: 0 }}><Panel title="Order Volume Trend" subtitle="Created uses PO creation date; completed uses buyer confirmation date."><VolumeTrend key={chartKey} points={orders.volumeTrend} /></Panel></View><View style={{ flex: wide ? 2 : undefined, minWidth: 0 }}><Panel title="Order Status" subtitle="Current status of orders created in the selected period.">{orders.statusDistribution.length ? <AnalyticsDonut rows={orders.statusDistribution.map(row => ({ label: row.label, value: row.count, percentage: row.percentage }))} center={number(current.totalOrders)} caption="Orders" /> : <Empty>No order activity in this period.</Empty>}</Panel></View></View>
    <View style={{ flexDirection: wide ? 'row' : 'column', gap: 14 }}><View style={{ flex: wide ? 3 : undefined, minWidth: 0 }}><Panel title="Fulfillment Stage Time" subtitle="Averages use only verified adjacent persisted timestamps.">{orders.stageDurations.length ? orders.stageDurations.map(stage => <View key={stage.stage} style={{ flexDirection: 'row', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10, borderBottomWidth: 1, borderColor: colors.border, paddingVertical: 10 }}><View><Text style={{ color: colors.text, fontSize: 12, fontWeight: '700' }}>{stage.stage}</Text><Text style={body}>Based on {number(stage.sampleCount)} orders</Text></View><Text style={{ color: colors.text, fontSize: 13, fontWeight: '800' }}>{hours(stage.averageHours)}</Text></View>) : <Empty>No completed orders with sufficient fulfillment timestamps.</Empty>}</Panel></View><View style={{ flex: wide ? 2 : undefined, minWidth: 0 }}><Panel title="Current Backlog" subtitle="Current non-terminal orders; not constrained by selected creation dates.">{orders.backlog.length ? orders.backlog.map(row => <View key={row.status} style={{ flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: colors.border, paddingVertical: 10 }}><Text style={{ color: colors.textSecondary, fontSize: 12 }}>{row.status}</Text><Text style={{ color: colors.text, fontWeight: '800' }}>{number(row.count)}</Text></View>) : <Empty>No active orders.</Empty>}<Text style={{ ...body, marginTop: 6 }}>Age since creation: {orders.aging.length ? orders.aging.map(row => row.bucket + ' ' + number(row.count)).join(' · ') : 'No active orders'}</Text></Panel></View></View>
    <View style={{ flexDirection: wide ? 'row' : 'column', gap: 14 }}><View style={{ flex: wide ? 3 : undefined, minWidth: 0 }}><Panel title="Delivery Performance" subtitle="Only delivered orders with an AGREED supplier delivery date are eligible; Manila dates are compared.">{orders.deliveryPerformance.eligibleOrders ? <View style={{ gap: 10 }}><Text style={{ color: colors.text, fontSize: 22, fontWeight: '800' }}>{orders.deliveryPerformance.onTimeRate?.toFixed(1)}% on time</Text><Text style={body}>{number(orders.deliveryPerformance.onTimeOrders)} on time · {number(orders.deliveryPerformance.lateOrders)} late · {number(orders.deliveryPerformance.eligibleOrders)} eligible · Average delay {orders.deliveryPerformance.averageDelayDays?.toFixed(1) ?? '—'} days</Text></View> : <Empty>No delivered orders with an agreed delivery target.</Empty>}</Panel></View><View style={{ flex: wide ? 2 : undefined, minWidth: 0 }}><Panel title="Longest Fulfillment" subtitle="Valid supplier-confirmation to buyer-confirmation timestamps.">{orders.slowestOrders.length ? orders.slowestOrders.map(order => <Pressable key={order.id} accessibilityRole="button" onPress={() => onView(order.id)} style={{ borderBottomWidth: 1, borderColor: colors.border, paddingVertical: 10, gap: 3 }}><Text style={{ color: colors.text, fontSize: 13, fontWeight: '700' }}>{order.poNumber} · {hours(order.fulfillmentHours)}</Text><Text style={body}>{order.buyerName} · Completed {dateTime(order.completedAt)}</Text></Pressable>) : <Empty>No completed orders with sufficient fulfillment timestamps.</Empty>}</Panel></View></View>
    <Panel title="Order Performance" subtitle="Orders created in the selected period. Export includes this loaded page only."><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ flexGrow: 0 }} contentContainerStyle={{ gap: 6 }}>{SORTS.map(sort => <Choice key={sort.key} label={'Sort: ' + sort.label} selected={options.orderSort === sort.key} disabled={busy} onPress={() => onOptionsChange({ orderSort: sort.key })} />)}</ScrollView><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}><Choice label={options.orderDirection === 'DESC' ? 'Descending ↓' : 'Ascending ↑'} disabled={busy} onPress={() => onOptionsChange({ orderDirection: options.orderDirection === 'DESC' ? 'ASC' : 'DESC' })} />{[20, 50, 100].map(limit => <Choice key={limit} label={limit + ' per page'} selected={options.orderLimit === limit} disabled={busy} onPress={() => onOptionsChange({ orderLimit: limit })} />)}</View>{busy && <Text accessibilityLiveRegion="polite" style={body}>Updating order performance… Previous results remain visible.</Text>}{page.items.length ? <OrderRows rows={page.items} table={width >= 1500} onView={onView} /> : <Empty>No orders were created in this period.</Empty>}<Text style={body}>{number(page.total)} orders · Page {page.page} of {page.totalPages} · Export includes this loaded order page.</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}><Choice label="Previous order page" disabled={busy || page.page <= 1} onPress={() => onOptionsChange({ orderPage: page.page - 1 })} /><Choice label="Next order page" disabled={busy || page.page >= page.totalPages} onPress={() => onOptionsChange({ orderPage: page.page + 1 })} /></View></Panel>
  </>
}
