import { StyleSheet } from 'react-native'
export const styles = StyleSheet.create({
     container: {
       flex: 1,
       backgroundColor: '#F9FAFB',
     },
     header: {
       padding: 20,
       backgroundColor: 'white',
       borderBottomWidth: 1,
       borderBottomColor: '#E5E7EB',
     },
     headerTitle: {
       fontSize: 24,
       fontWeight: '800',
       color: '#1F2937',
     },
     content: {
       flex: 1,
     },
     section: {
       marginBottom: 24,
     },
     sectionTitle: {
       fontSize: 16,
       fontWeight: '600',
       color: '#374151',
       marginBottom: 12,
       marginHorizontal: 20,
     },
     profileCard: {
       flexDirection: 'row',
       alignItems: 'center',
       backgroundColor: 'white',
       margin: 20,
       padding: 20,
       borderRadius: 16,
       shadowColor: '#000',
       shadowOffset: { width: 0, height: 2 },
       shadowOpacity: 0.1,
       shadowRadius: 4,
       elevation: 3,
     },
     profileImage: {
       width: 60,
       height: 60,
       borderRadius: 30,
       marginRight: 16,
     },
     profileInfo: {
       flex: 1,
     },
     profileName: {
       fontSize: 18,
       fontWeight: '700',
       color: '#1F2937',
       marginBottom: 4,
     },
     profileEmail: {
       fontSize: 14,
       color: '#6B7280',
       marginBottom: 8,
     },
     roleBadge: {
       alignSelf: 'flex-start',
       backgroundColor: '#EBF4FF',
       paddingHorizontal: 12,
       paddingVertical: 4,
       borderRadius: 12,
     },
     roleText: {
       fontSize: 12,
       fontWeight: '600',
       color: '#3B82F6',
     },
     settingsGroup: {
       backgroundColor: 'white',
       marginHorizontal: 20,
       borderRadius: 12,
       shadowColor: '#000',
       shadowOffset: { width: 0, height: 1 },
       shadowOpacity: 0.1,
       shadowRadius: 2,
       elevation: 2,
     },
     settingItem: {
       flexDirection: 'row',
       alignItems: 'center',
       justifyContent: 'space-between',
       padding: 16,
  
       borderBottomColor: '#F3F4F6',
     },
     settingLeft: {
       flexDirection: 'row',
       alignItems: 'center',
       flex: 1,
     },
     iconContainer: {
       width: 40,
       height: 40,
       backgroundColor: '#F3F4F6',
       borderRadius: 20,
       alignItems: 'center',
       justifyContent: 'center',
       marginRight: 12,
     },
     settingText: {
       flex: 1,
     },
     settingTitle: {
       fontSize: 16,
       fontWeight: '600',
       color: '#1F2937',
       marginBottom: 2,
     },
     settingSubtitle: {
       fontSize: 14,
       color: '#6B7280',
     },
     settingRight: {
       flexDirection: 'row',
       alignItems: 'center',
       gap: 8,
     },
     logoutButton: {
       flexDirection: 'row',
       alignItems: 'center',
       justifyContent: 'center',
       backgroundColor: 'white',
       marginHorizontal: 20,
       padding: 16,
       borderRadius: 12,
       gap: 8,
       shadowColor: '#000',
       shadowOffset: { width: 0, height: 1 },
       shadowOpacity: 0.1,
       shadowRadius: 2,
       elevation: 2,
     },
     logoutText: {
       fontSize: 16,
       fontWeight: '600',
       color: '#EF4444',
     },
   });