import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Building2, RefreshCw, ShieldCheck, UsersRound, WalletCards } from 'lucide-react-native';
import { useTheme } from '@/contexts/ThemeContext';
import { Kpis } from '@/components/Kpi';
import { adminGovernanceService, GovernanceTab } from '@/services/adminGovernanceService';
import { GovernanceManagementPanel } from './GovernanceManagementPanel';

const php = (value: number) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(value ?? 0);

export default function GovernanceScreen() {
  const { colors } = useTheme();
  const [tab, setTab] = useState<GovernanceTab>('overview'); const [dashboard, setDashboard] = useState<any>(); const [wallet, setWallet] = useState<any>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { const [d, w] = await Promise.all([adminGovernanceService.dashboard(), adminGovernanceService.wallet({ page: 1, limit: 30 })]); setDashboard(d.adminGovernanceDashboard); setWallet(w.platformWallet); } catch (requestError: any) { setError(requestError.message ?? 'Unable to load platform governance data.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const styles = makeStyles(colors);
  const tabs: Array<[GovernanceTab, string]> = [['overview', 'Overview'], ['organizations', 'Organizations'], ['wallet', 'Platform Wallet']];
  return <ScrollView style={styles.root} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.title}>Kompra Administration</Text><Text style={styles.subtitle}>Platform governance, verification, security and financial oversight.</Text></View><Pressable accessibilityLabel="Refresh platform governance" onPress={() => void load()} style={styles.refresh}><RefreshCw size={18} color="#fff" /><Text style={styles.refreshText}>Refresh</Text></Pressable></View>
    <View style={styles.tabs}>{tabs.map(([key, text]) => <Pressable key={key} onPress={() => setTab(key)} style={[styles.tab, tab === key && styles.tabActive]}><Text style={[styles.tabText, tab === key && styles.tabTextActive]}>{text}</Text></Pressable>)}</View>
    {loading ? <View style={styles.state}><ActivityIndicator color="#7C3AED" /><Text style={styles.muted}>Loading governance data…</Text></View> : error ? <View style={styles.state}><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()} style={styles.retry}><Text style={styles.retryText}>Retry</Text></Pressable></View> : <>
      {tab === 'overview' && dashboard && <><Kpis items={[{ title: 'Organizations', value: String(dashboard.totalOrganizations), subtitle: `${dashboard.pendingOrganizations} pending reviews`, icon: Building2, accent: '#2563EB' }, { title: 'Standalone Agents', value: String(dashboard.totalStandaloneAgents), subtitle: `${dashboard.verifiedStandaloneAgents} verified`, icon: UsersRound, accent: '#0F766E' }, { title: 'Platform Wallet', value: php(dashboard.platformWalletBalance), subtitle: `${php(dashboard.platformFees30Days)} / 30 days`, icon: WalletCards, accent: '#7C3AED' }, { title: 'Successful Payments', value: String(dashboard.successfulPaymentCount), subtitle: `${php(dashboard.platformFeesToday)} fees today`, icon: ShieldCheck, accent: '#D97706' }]} /><View style={styles.summary}><Text style={styles.sectionTitle}>Review queue</Text><Text style={styles.summaryText}>{dashboard.pendingOrganizations} organizations and {dashboard.pendingStandaloneAgents} standalone agents are awaiting verification.</Text></View></>}
      {tab === 'organizations' && <GovernanceManagementPanel type="organizations" onChanged={() => void load()} />}
      {tab === 'wallet' && <><Kpis items={[{ title: 'Available Platform Revenue', value: php(wallet?.balance), icon: WalletCards, accent: '#7C3AED' }]} /><Text style={styles.sectionTitle}>Platform wallet ledger</Text><GovernanceManagementPanel type="wallet" onChanged={() => void load()} /></>}
    </>}
  </ScrollView>;
}

const makeStyles = (colors: any) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, content: { padding: 18, gap: 16, maxWidth: 1320, width: '100%', alignSelf: 'center' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16 }, title: { color: colors.text, fontSize: 25, fontWeight: '900' }, subtitle: { color: colors.textSecondary, marginTop: 5, fontSize: 13 }, refresh: { backgroundColor: '#7C3AED', borderRadius: 10, paddingHorizontal: 13, paddingVertical: 10, flexDirection: 'row', gap: 7, alignItems: 'center' }, refreshText: { color: '#fff', fontWeight: '800' }, tabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, tab: { paddingHorizontal: 13, paddingVertical: 9, borderRadius: 9, borderWidth: 1, borderColor: colors.border }, tabActive: { backgroundColor: '#7C3AED', borderColor: '#7C3AED' }, tabText: { color: colors.textSecondary, fontWeight: '700', fontSize: 13 }, tabTextActive: { color: '#fff' }, state: { minHeight: 220, justifyContent: 'center', alignItems: 'center', gap: 12 }, muted: { color: colors.textSecondary }, error: { color: '#DC2626', textAlign: 'center' }, retry: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 9 }, retryText: { color: colors.text, fontWeight: '700' }, summary: { borderColor: colors.border, borderWidth: 1, borderRadius: 14, backgroundColor: colors.surface, padding: 16 }, sectionTitle: { color: colors.text, fontWeight: '900', fontSize: 17 }, summaryText: { color: colors.textSecondary, marginTop: 7 }, search: { color: colors.text, borderColor: colors.border, borderWidth: 1, backgroundColor: colors.surface, paddingHorizontal: 13, paddingVertical: 11, borderRadius: 10 }, resultCount: { color: colors.textSecondary, fontSize: 12, fontWeight: '700' }, row: { flexDirection: 'row', gap: 12, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 14, backgroundColor: colors.surface, alignItems: 'center' }, rowTitle: { color: colors.text, fontWeight: '800', fontSize: 15 }, rowMeta: { color: colors.textSecondary, marginTop: 4, fontSize: 12 }, badge: { color: '#2563EB', backgroundColor: '#DBEAFE', overflow: 'hidden', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3, fontSize: 10, fontWeight: '800' }, danger: { color: '#B91C1C', backgroundColor: '#FEE2E2' }, sandbox: { color: '#92400E', backgroundColor: '#FEF3C7' }, amount: { fontSize: 14, fontWeight: '900' } });
