import React, { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { MoreHorizontal } from 'lucide-react-native';
import { useTheme } from '@/contexts/ThemeContext';
import { AdminDataTable, AdminDataTableColumn } from '@/components/admin/AdminDataTable';
import { AdminPagination } from '@/components/admin/AdminPagination';
import { AdminStatusBadge } from '@/components/admin/AdminStatusBadge';
import { AdminEntityManagementModal, ManagedEntity, ManagementAction } from '@/components/admin/AdminEntityManagementModal';
import { adminGovernanceService } from '@/services/adminGovernanceService';

type Organization = { id: number; name: string; email?: string | null; roles: string[]; verificationStatus: string; accountStatus: string; createdAt: string; suspensionReason?: string | null; banReason?: string | null };
type Ledger = { id: string; sourceType: string; referenceId?: string | null; amount: number; balanceAfter: number; environment: string; createdAt: string };
type Page<T> = { items: T[]; total: number; page: number; limit: number };
const human = (value: string) => value.replace(/_/g, ' ');
const currency = (value: number) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(value);

export function GovernanceManagementPanel({ type, onChanged }: { type: 'organizations' | 'wallet'; onChanged: () => void }) {
  const { colors } = useTheme(); const { width } = useWindowDimensions(); const isDesktop = width >= 1100; const styles = makeStyles(colors);
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(30); const [search, setSearch] = useState(''); const [verification, setVerification] = useState<string>(); const [account, setAccount] = useState<string>(); const [data, setData] = useState<Page<Organization> | Page<Ledger>>({ items: [], total: 0, page: 1, limit: 30 }); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [selected, setSelected] = useState<Organization | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { if (type === 'organizations') { const response = await adminGovernanceService.organizations({ search: search || undefined, verificationStatus: verification, accountStatus: account, page, limit: pageSize }); setData(response.adminOrganizations); } else { const response = await adminGovernanceService.wallet({ page, limit: pageSize }); setData(response.platformWalletLedger); } } catch (cause: any) { setError(cause.message ?? 'Unable to load records.'); } finally { setLoading(false); } }, [type, page, pageSize, search, verification, account]);
  useEffect(() => { void load(); }, [load]);
  const reset = (setter: (value: any) => void, value: any) => { setter(value); setPage(1); };
  const orgColumns: AdminDataTableColumn<Organization>[] = [{ key: 'name', label: 'Organization', flex: 2, render: row => <View><Text style={[styles.primary, { color: colors.text }]}>{row.name}</Text>{row.email ? <Text style={[styles.secondary, { color: colors.textSecondary }]}>{row.email}</Text> : null}</View> }, { key: 'roles', label: 'Role', flex: 1, render: row => <Text style={[styles.primary, { color: colors.textSecondary }]}>{row.roles.map(human).join(' + ')}</Text> }, { key: 'verification', label: 'Verification', flex: 1, render: row => <AdminStatusBadge value={row.verificationStatus} /> }, { key: 'account', label: 'Account Status', flex: 1, render: row => <AdminStatusBadge value={row.accountStatus} /> }, { key: 'created', label: 'Created', flex: 1, render: row => <Text style={[styles.primary, { color: colors.textSecondary }]}>{new Date(row.createdAt).toLocaleDateString()}</Text> }, { key: 'actions', label: 'Actions', width: 70, render: row => <Pressable accessibilityLabel={`Manage ${row.name}`} onPress={() => setSelected(row)} style={styles.action}><MoreHorizontal size={19} color={colors.text} /></Pressable> }];
  const ledgerColumns: AdminDataTableColumn<Ledger>[] = [{ key: 'date', label: 'Date', flex: 1, render: row => <Text style={[styles.primary, { color: colors.textSecondary }]}>{new Date(row.createdAt).toLocaleDateString()}</Text> }, { key: 'source', label: 'Source', flex: 1.3, render: row => <Text style={[styles.primary, { color: colors.text }]}>{human(row.sourceType)}</Text> }, { key: 'reference', label: 'Reference', flex: 1.5, render: row => <Text style={[styles.secondary, { color: colors.textSecondary }]}>{row.referenceId ?? '—'}</Text> }, { key: 'amount', label: 'Amount', flex: 1, render: row => <Text style={[styles.primary, { color: row.amount >= 0 ? '#22C55E' : '#EF4444' }]}>{currency(row.amount)}</Text> }, { key: 'balance', label: 'Balance After', flex: 1, render: row => <Text style={[styles.primary, { color: colors.text }]}>{currency(row.balanceAfter)}</Text> }, { key: 'environment', label: 'Environment', flex: 1, render: row => <AdminStatusBadge value={row.environment} /> }];
  const actions = selected ? organizationActions(selected) : [];
  const manage = async (action: ManagementAction, reason?: string) => { if (!selected) return; await adminGovernanceService.mutateOrganization(action.mutation, selected.id, reason); await load(); onChanged(); };
  return <View style={styles.root}>{type === 'organizations' && <><TextInput value={search} onChangeText={value => reset(setSearch, value)} placeholder="Search organizations…" placeholderTextColor={colors.textSecondary} style={styles.search} /><ScrollView horizontal style={styles.filterScroll} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filter('All', !verification, () => reset(setVerification, undefined))}{['VERIFIED','PENDING','UNVERIFIED','EXPIRED'].map(value => filter(human(value), verification === value, () => reset(setVerification, value)))}<View style={styles.separator} />{filter('Active', account === 'ACTIVE', () => reset(setAccount, 'ACTIVE'))}{filter('Suspended', account === 'SUSPENDED', () => reset(setAccount, 'SUSPENDED'))}{filter('Banned', account === 'BANNED', () => reset(setAccount, 'BANNED'))}</ScrollView></>}{error ? <View style={styles.errorState}><Text style={{ color: colors.error }}>{error}</Text><Pressable onPress={() => void load()}><Text style={{ color: colors.primary, fontWeight: '800' }}>Retry</Text></Pressable></View> : isDesktop ? <AdminDataTable columns={type === 'organizations' ? orgColumns : ledgerColumns} data={data.items as any[]} keyExtractor={row => String((row as any).id)} loading={loading} emptyState="No matching records found." onRowPress={type === 'organizations' ? row => setSelected(row as Organization) : undefined} minWidth={type === 'organizations' ? 960 : 900} /> : <MobileCards data={data.items as any[]} type={type} onSelect={row => setSelected(row as Organization)} colors={colors} />}{data.total > 0 && <AdminPagination page={page} total={data.total} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={size => { setPageSize(size); setPage(1); }} />}<AdminEntityManagementModal entity={selected ? toManagedEntity(selected) : null} actions={actions} onClose={() => setSelected(null)} onAction={manage} /></View>;
  function filter(label: string, active: boolean, onPress: () => void) { return <Pressable key={label} onPress={onPress} style={[styles.filter, { backgroundColor: active ? colors.primary : colors.border }]}><Text style={{ color: active ? '#fff' : colors.textSecondary, fontSize: 12, fontWeight: '700' }}>{label}</Text></Pressable>; }
}
function organizationActions(org: Organization): ManagementAction[] { const actions: ManagementAction[] = []; if (org.verificationStatus !== 'VERIFIED') actions.push({ label: 'Approve Verification', mutation: 'adminApproveOrganizationVerification' }, { label: 'Reject Verification', mutation: 'adminRejectOrganizationVerification', requiresReason: true, destructive: true }); if (org.accountStatus === 'ACTIVE') actions.push({ label: 'Suspend Organization', mutation: 'adminSuspendOrganization', requiresReason: true, destructive: true }, { label: 'Ban Organization', mutation: 'adminBanOrganization', requiresReason: true, destructive: true }); if (org.accountStatus === 'SUSPENDED') actions.push({ label: 'Restore Organization', mutation: 'adminRestoreOrganization' }, { label: 'Ban Organization', mutation: 'adminBanOrganization', requiresReason: true, destructive: true }); if (org.accountStatus === 'BANNED') actions.push({ label: 'Unban Organization', mutation: 'adminUnbanOrganization' }); return actions; }
function toManagedEntity(org: Organization): ManagedEntity { return { id: org.id, name: org.name, subtitle: org.roles.map(human).join(' • '), verificationStatus: org.verificationStatus, accountStatus: org.accountStatus, createdAt: org.createdAt, details: [['Email', org.email], ['Enforcement reason', org.banReason ?? org.suspensionReason]] }; }
function MobileCards({ data, type, onSelect, colors }: { data: Array<Organization | Ledger>; type: 'organizations' | 'wallet'; onSelect: (row: Organization) => void; colors: any }) { return <View style={{ gap: 9 }}>{data.map(row => type === 'organizations' ? <Pressable key={row.id} onPress={() => onSelect(row as Organization)} style={{ borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 12, padding: 14, gap: 7 }}><Text style={{ color: colors.text, fontWeight: '800' }}>{(row as Organization).name}</Text><Text style={{ color: colors.textSecondary, fontSize: 12 }}>{(row as Organization).roles.map(human).join(' • ')}</Text><View style={{ flexDirection: 'row', gap: 6 }}><AdminStatusBadge value={(row as Organization).verificationStatus} /><AdminStatusBadge value={(row as Organization).accountStatus} /></View></Pressable> : <View key={row.id} style={{ borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 12, padding: 14 }}><Text style={{ color: colors.text, fontWeight: '800' }}>{human((row as Ledger).sourceType)}</Text><Text style={{ color: colors.textSecondary, marginTop: 4 }}>{currency((row as Ledger).amount)}</Text></View>)}</View>; }
const makeStyles = (colors: any) => StyleSheet.create({ root: { width: '100%', alignSelf: 'stretch', gap: 12 }, search: { color: colors.text, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 11, borderRadius: 10 }, filterScroll: { width: '100%', flexGrow: 0, flexShrink: 0, height: 44, maxHeight: 44 }, filters: { height: 44, alignItems: 'center', gap: 7 }, filter: { alignSelf: 'center', paddingVertical: 7, paddingHorizontal: 11, borderRadius: 18 }, separator: { width: 1, height: 22, backgroundColor: colors.border, marginHorizontal: 2 }, primary: { fontSize: 13, fontWeight: '700' }, secondary: { fontSize: 11, marginTop: 3 }, action: { width: 34, height: 34, justifyContent: 'center', alignItems: 'center', borderRadius: 8, backgroundColor: colors.border }, errorState: { minHeight: 150, justifyContent: 'center', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: colors.border, borderRadius: 12 } });
