// @/components/admin/AdminEntityManagementModal.tsx
import React, { useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useTheme } from '@/contexts/ThemeContext';

export type ManagedEntity = { id: string | number; name: string; subtitle?: string; verificationStatus: string; accountStatus: string; createdAt: string; details?: Array<[string, string | undefined | null]> };
export type ManagementAction = { label: string; mutation: string; requiresReason?: boolean; destructive?: boolean };
export function AdminEntityManagementModal({ entity, actions, onClose, onAction }: { entity: ManagedEntity | null; actions: ManagementAction[]; onClose: () => void; onAction: (action: ManagementAction, reason?: string) => Promise<void> }) {
  const { colors } = useTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const [pending, setPending] = useState<ManagementAction | null>(null); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  if (!entity) return null;
  const execute = async () => { if (!pending) return; if (pending.requiresReason && !reason.trim()) { setError('A reason is required.'); return; } setSaving(true); setError(undefined); try { await onAction(pending, reason.trim() || undefined); setPending(null); setReason(''); onClose(); } catch (cause: any) { setError(cause?.message ?? 'The action could not be completed.'); } finally { setSaving(false); } };
  return <Modal visible transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.backdrop} onPress={onClose}><Pressable style={styles.card} onPress={() => {}}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{pending ? pending.label : entity.name}</Text>{pending ? <><Text style={styles.message}>This action changes protected Kompra account access for {entity.name}.</Text>{pending.requiresReason && <TextInput value={reason} onChangeText={setReason} multiline placeholder="Reason *" placeholderTextColor={colors.textSecondary} style={styles.reason} accessibilityLabel="Required action reason" />}{error && <Text style={styles.error}>{error}</Text>}<View style={styles.buttons}><Pressable disabled={saving} onPress={() => { setPending(null); setReason(''); setError(undefined); }} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable><Pressable disabled={saving} onPress={execute} style={[styles.confirm, pending.destructive && { backgroundColor: colors.error }]}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.confirmText}>{pending.label}</Text>}</Pressable></View></> : <><Text style={styles.subtitle}>{entity.subtitle}</Text><View style={styles.info}><Info label="Verification" value={entity.verificationStatus} /><Info label="Account Status" value={entity.accountStatus} /><Info label="Created" value={new Date(entity.createdAt).toLocaleDateString()} />{entity.details?.map(([label, value]) => value ? <Info key={label} label={label} value={value} /> : null)}</View><View style={styles.actions}>{actions.map(action => <Pressable key={action.mutation} onPress={() => { if (action.requiresReason) { setPending(action); } else { void onAction(action).then(onClose); } }} style={[styles.action, action.destructive && { borderColor: colors.error }]}><Text style={[styles.actionText, action.destructive && { color: colors.error }]}>{action.label}</Text></Pressable>)}</View><Pressable onPress={onClose} style={styles.close}><Text style={styles.cancelText}>Close</Text></Pressable></>}</ScrollView></Pressable></Pressable></Modal>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={stylesInfo.row}><Text style={stylesInfo.label}>{label}</Text><Text style={stylesInfo.value}>{value.replace(/_/g, ' ')}</Text></View>; }
const stylesInfo = StyleSheet.create({ row: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, label: { color: '#64748B', fontSize: 12 }, value: { color: '#E2E8F0', fontSize: 12, fontWeight: '700', textAlign: 'right', flex: 1 } });
const makeStyles = (colors: any) => StyleSheet.create({ backdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20, backgroundColor: 'rgba(0,0,0,.58)' }, card: { width: '100%', maxWidth: 520, maxHeight: '90%', borderRadius: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, content: { padding: 20, gap: 14 }, title: { color: colors.text, fontSize: 19, fontWeight: '900' }, subtitle: { color: colors.textSecondary }, message: { color: colors.textSecondary, lineHeight: 20 }, info: { gap: 11, padding: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 12 }, actions: { gap: 8 }, action: { minHeight: 44, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 9 }, actionText: { color: colors.text, fontWeight: '800' }, close: { minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: colors.background }, cancelText: { color: colors.text, fontWeight: '800' }, reason: { minHeight: 92, color: colors.text, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 11, textAlignVertical: 'top' }, error: { color: colors.error, fontSize: 12 }, buttons: { flexDirection: 'row', gap: 10 }, cancel: { flex: 1, minHeight: 45, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 9 }, confirm: { flex: 1, minHeight: 45, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary, borderRadius: 9 }, confirmText: { color: '#fff', fontWeight: '800' } });
