// BluetoothEvents.ts
export const BTEvents = {
     EVENT_DEVICE_ALREADY_PAIRED: 'EVENT_DEVICE_ALREADY_PAIRED',
     EVENT_DEVICE_FOUND: 'EVENT_DEVICE_FOUND',
     EVENT_CONNECTION_LOST: 'EVENT_CONNECTION_LOST',
     EVENT_UNABLE_CONNECT: 'EVENT_UNABLE_CONNECT',
     EVENT_CONNECTED: 'EVENT_CONNECTED',
     EVENT_BLUETOOTH_NOT_SUPPORT: 'EVENT_BLUETOOTH_NOT_SUPPORT',
   };
   