import { StyleSheet} from 'react-native'
export const styles = StyleSheet.create({
     overlay: {
       position: 'absolute',
       top: 0,
       left: 0,
       right: 0,
       bottom: 0,
       backgroundColor: '#222222',
       zIndex: 998,
     },
     overlayTouchable: {
       flex: 1,
     },
     mobileSidebar: {
       position: 'absolute',
       top: 0,
       bottom: 0,
       backgroundColor: 'white',
       zIndex: 999,
       shadowColor: '#000',
       shadowOffset: { width: 0, height: 0 },
       shadowOpacity: 0.25,
       shadowRadius: 10,
       elevation: 10,
   
     },
     desktopSidebar: {
      left: 0,
       backgroundColor: 'white',
       borderRightWidth: 1,
       borderRightColor: '#E5E7EB',
       shadowColor: '#000',
       shadowOffset: { width: -2, height: 0},
       shadowOpacity: 0.1,
       shadowRadius: 4,
       elevation: 4,
     },
     header: {
       flexDirection: 'row',
       alignItems: 'center',
       justifyContent: 'space-between',
       padding: 16,
       borderBottomWidth: 1,
       borderBottomColor: '#E5E7EB',
       backgroundColor: '#F9FAFB',
     },
     closeButton: {
       padding: 4,
       backgroundColor: '#F3F4F6',
       borderRadius: 8,
     },
     headerCenter: {
       flexDirection: 'row',
       gap: 10,
       alignItems: 'center',
       flex: 1,
     },
     logo: {
       width: 50,
       height: 50,
       borderRadius: 25,
       marginBottom: 6,
     },
     companyName: {
       fontSize: 16,
       fontWeight: '700',
       color: '#1F2937',
     },
     toggleButton: {
       padding: 8,
       backgroundColor: '#F3F4F6',
       borderRadius: 8,
     },
     itemsList: {
       flex: 1,
       padding: 16,
     },
     emptyCart: {
       flex: 1,
       alignItems: 'center',
       justifyContent: 'center',
       paddingTop: 60,
     },
     emptyText: {
       fontSize: 16,
       fontWeight: '600',
       color: '#6B7280',
       marginTop: 12,
     },
     emptySubtext: {
       fontSize: 14,
       color: '#9CA3AF',
       marginTop: 4,
     },
     cartItem: {
       flexDirection: 'row',
       paddingVertical: 12,
       borderBottomWidth: 1,
       borderBottomColor: '#F3F4F6',
     },
     itemImage: {
       width: 50,
       height: 50,
       borderRadius: 8,
       backgroundColor: '#F3F4F6',
     },
     itemDetails: {
       flex: 1,
       marginLeft: 12,
     },
     itemName: {
       fontSize: 14,
       fontWeight: '600',
       color: '#1F2937',
       marginBottom: 4,
     },
     itemPrice: {
       fontSize: 12,
       color: '#6B7280',
       marginBottom: 8,
     },
     quantityContainer: {
       flexDirection: 'row',
       alignItems: 'center',
     },
     quantityButton: {
       width: 28,
       height: 28,
       backgroundColor: '#F3F4F6',
       borderRadius: 6,
       alignItems: 'center',
       justifyContent: 'center',
     },
     quantityButtonText: {
       fontSize: 16,
       fontWeight: '600',
       color: '#374151',
     },
     quantityInput: {
       width: 41,
       height: 41,
       textAlign: 'center',
       fontSize: 14,
       fontWeight: '600',
       marginHorizontal: 4,
       backgroundColor: '#F9FAFB',
       borderRadius: 4,
       borderWidth: 1,
       borderColor: '#E5E7EB',
     },
     itemRight: {
       alignItems: 'flex-end',
       justifyContent: 'space-between',
     },
     subtotal: {
       fontSize: 14,
       fontWeight: '700',
       color: '#1F2937',
     },
     removeButton: {
       padding: 4,
     },
     footer: {
       height: 150,
       padding: 16,
       borderTopWidth: 1,
       borderTopColor: '#E5E7EB',
       backgroundColor: '#F9FAFB',
     },
     totalContainer: {
       flexDirection: 'row',
       justifyContent: 'space-between',
       alignItems: 'center',
       marginBottom: 16,
     },
     totalLabel: {
       fontSize: 18,
       fontWeight: '700',
       color: '#1F2937',
     },
     totalAmount: {
       fontSize: 24,
       fontWeight: '800',
       color: '#3B82F6',
     },
     buttonContainer: {
       flexDirection: 'row',
       gap: 8,
     },
   
     actionButton: {
       flex: 1,
       flexDirection: 'row',
       alignItems: 'center',
       justifyContent: 'center',
       paddingVertical: 12,
       paddingHorizontal: 16,
       borderRadius: 8,
       gap: 6,
     },
     clearButton: {
       backgroundColor: '#FEF2F2',
       borderWidth: 1,
       borderColor: '#FECACA',
     },
     checkoutButton: {
       backgroundColor: '#3B82F6',
     },
     actionButtonText: {
       fontSize: 14,
       fontWeight: '600',
     },
     checkoutButtonText: {
       fontSize: 14,
       fontWeight: '600',
       color: 'white',
     },
   });